name: "Docker Release - Generic"

on:
  workflow_call:
    inputs:
      image-artifact-backend:
        type: string
        default: 'registry'
        description: >
          The method used for sharing the image artifact between jobs.
          
          The 'gh-artifacts' method downloads and loads an exported Docker Image Tarball, that was uploaded to GitHub Actions Storage in a previous CI job.
          The 'registry' method **copies** the image from a source image registry to the target registry if a source registry is configured. Otherwise builds from cache.

          Options:
          - 'gh-artifacts': Share the image artifact as Tarball, uploaded/downloaded via Github Artifact Storage.
          - 'registry': Share the image artifact via a source registry. When this option is used, all 'source-*' inputs params need to be provided. Also both 'source-registry-username', 'source-registry-token' need to be provided or alternatively 'token' can be used when the registry is `ghcr.io` and the token has appropriate permissions.

          default: 'registry'
        required: false

      registry-prefix:
        description: >
          DEPRECATED in favor of 'image-registry'.

          Image registry prefix (e.g. ghcr.io, docker.io)
        type: string
        required: false
        default: 'ghcr.io'
      docker-image-repo:
        description: >
          DEPRECATED in favor of 'image-repo'.

          Docker image repository. Default -> GitHub repository owner/organisation.
        type: string
        required: false
        default: ${{ github.repository_owner }}
      docker-image-name:
        description: >
          DEPRECATED in favor of 'image-name'.
          
          Docker image name. Default -> GitHub repository name.
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      image-registry:
        description: >
          Target image registry prefix (e.g. ghcr.io, docker.io)

          Default: 'ghcr.io'
        type: string
        required: false
        default: ${{ inputs.registry-prefix || 'ghcr.io' }}
      image-repo:
        description: >
          Target image repository(e.g. wearefrank, my-github-username).

          Default -> GitHub repository owner/organisation ('github.repository_owner').
        type: string
        required: false
        default: ${{ inputs.docker-image-repo || github.repository_owner }}
      image-name:
        description: >
          Target image name(e.g. zaakbrug, frankframework).
          
          default -> GitHub repository name ('github.event.repository.name').
        type: string
        required: false
        default: ${{ inputs.docker-image-name || github.event.repository.name }}
      source-image-registry:
        description: >
          Source image registry prefix (e.g. ghcr.io, docker.io)

          Default: 'ghcr.io'
        type: string
        required: false
        default: 'ghcr.io'
      source-image-repo:
        description: >
          Source image repository(e.g. wearefrank, my-github-username).
          
          Default -> GitHub repository owner/organisation ('github.repository_owner').
        type: string
        required: false
        default: ${{ github.repository_owner }}
      source-image-name:
        description: >
          Source image name(e.g. zaakbrug, frankframework).
          
          default -> GitHub repository name ('github.event.repository.name') + '-staging'.
        type: string
        required: false
        default: ${{ github.event.repository.name }}-staging
      version:
        type: string
        required: false
        description: Semvers string. If empty, the ref/tag will be used (if on.tag trigger).
        default: ''
      latest-tag:
        type: boolean
        required: false
        description: Add latest flavor
        default: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
    secrets:
      token: 
        description: >
          GitHub token with permissions to access the repository.

          Default: GitHub token (secrets.GITHUB_TOKEN)
        required: false
      registry-username:
        description: >
          Username for the target image registry to push the image to.

          Default -> GitHub actor username (github.actor).
        required: false
      registry-token:
        description: >
          Token for the target image registry to push the image to.

          Default -> If the registry is `ghcr.io`, 'secrets.token' is used.
        required: false
      source-registry-username:
        description: >
          Username for the source image registry to copy the image.

          Only required when `image-artifact-backend: 'registry'`.

          default: GitHub actor username (github.actor).
        required: false
      source-registry-token:
        description: >
          Token for the source image registry to copy the image.

          Only required when `image-artifact-backend: 'registry'`.

          Default -> If the registry is `ghcr.io`, 'secrets.token' is used.
        required: false
    outputs:
      image-id: 
        value: ${{ jobs.publish.outputs.image-id }}
      image-digest: 
        value: ${{ jobs.publish.outputs.image-digest }}
      bake-file: 
        value: ${{ jobs.publish.outputs.bake-file }}
      image-metadata: 
        value: ${{ jobs.publish.outputs.image-metadata }}
      docker-meta-tags: 
        value: ${{ jobs.publish.outputs.docker-meta-tags }}
      docker-meta-labels: 
        value: ${{ jobs.publish.outputs.docker-meta-labels }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    outputs:
      docker-meta-tags: ${{ steps.meta.outputs.tags }}
      docker-meta-labels: ${{ steps.meta.outputs.labels }}
      bake-file: ${{ steps.meta.outputs.json }}
      image-id: ${{ steps.build-tarball.outputs.imageid }}
      image-digest: ${{ steps.build-tarball.outputs.digest }}
      image-metadata: ${{ steps.build-tarball.outputs.metadata }}
    steps:
    - uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
      with:
        disable-sudo: true
        egress-policy: audit
        allowed-endpoints: >
          api.github.com:443
          auth.docker.io:443
          github.com:443
          production.cloudflare.docker.com:443
          registry-1.docker.io:443

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
      with:
        token: ${{ secrets.token }}

    - name: Download Pre-build Artifacts
      if: inputs.image-artifact-backend == 'gh-artifacts'
      uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 #8.0.0
      with:
        pattern: pre-build-*
        merge-multiple: true

    - name: Download Build Artifacts
      if: inputs.image-artifact-backend == 'gh-artifacts'
      uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 #8.0.0
      with:
        pattern: build-*
        merge-multiple: true

    - name: Extract Image Metadata
      id: meta
      uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf #6.0.0
      with:
        images: ${{ inputs.image-registry }}/${{ inputs.image-repo }}/${{ inputs.image-name }}
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
          type=semver,pattern={{major}},value=${{ inputs.version }}
          type=ref,event=pr
          type=raw,value=latest,enable=${{ inputs.latest-tag }}
        flavor: |
          latest=false

    - name: Set up QEMU
      if: inputs.image-artifact-backend == 'gh-artifacts'
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a #4.0.0

    - name: Set up Docker Buildx
      if: inputs.image-artifact-backend == 'gh-artifacts'
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #4.0.0

    - name: Login To Target Container Registry
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # 4.0.0
      with:
        registry: ${{ inputs.image-registry }}
        username: ${{ secrets.registry-username == '' && github.actor || secrets.registry-username }}
        password: ${{ secrets.registry-token == '' && inputs.image-registry == 'ghcr.io' && secrets.token || secrets.registry-token }}
    
    - name: Build From GHA Cache And Push To Registry
      if: inputs.image-artifact-backend == 'gh-artifacts'
      id: build-tarball
      uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 #7.0.0
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        outputs: type=registry,oci-mediatypes=true,compression=estargz,compression-level=7,force-compression=true
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: true
        sbom: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Login To Source Container Registry
      if: inputs.image-artifact-backend == 'registry' && (inputs.source-image-repo || inputs.source-image-name)
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # 4.0.0
      with:
        registry: ${{ inputs.source-image-registry }}
        username: ${{ secrets.source-registry-username == '' && github.actor || secrets.source-registry-username }}
        password: ${{ secrets.source-registry-token == '' && inputs.source-image-registry == 'ghcr.io' && secrets.token || secrets.source-registry-token }}

    - name: Build Ref Source Registry
      if: inputs.image-artifact-backend == 'registry'
      id: build-ref-source-registry
      shell: bash
      env:
        IMAGE_REGISTRY: ${{ inputs.source-image-registry }}
        IMAGE_REPO: ${{ inputs.source-image-repo }}
        IMAGE_NAME: ${{ inputs.source-image-name }}
      run: |
        IMAGE_REF=""
        if [[ -n "${IMAGE_REGISTRY}" ]]; then
          IMAGE_REF+="${IMAGE_REGISTRY@L}/"
        fi
        if [[ -n "${IMAGE_REPO}" ]]; then
          IMAGE_REF+="${IMAGE_REPO@L}/"
        fi
        if [[ -n "${IMAGE_NAME}" ]]; then
          IMAGE_REF+="${IMAGE_NAME@L}"
        fi

        if [[ -n "${IMAGE_REF}" && -n "${IMAGE_DIGEST}" ]]; then
          IMAGE_REF+="@${IMAGE_DIGEST}"
        elif [[ -n "${IMAGE_REF}" && -n "${IMAGE_TAG}"  ]]; then
          IMAGE_REF+=":${IMAGE_TAG@L}"
        fi

        echo "image-ref=$IMAGE_REF" >> "$GITHUB_OUTPUT"
        echo "Image Ref ([<registry>/][<repo>/]<name>[:<tag>|@<digest>]): [$IMAGE_REF]"

    - name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 #6.3.0
      if: inputs.image-artifact-backend == 'registry'
      with:
        go-version: 1.26

    - name: Install Crane
      uses: imjasonh/setup-crane@6da1ae018866400525525ce74ff892880c099987 #0.5
      if: inputs.image-artifact-backend == 'registry'

    - name: Copy Image From Source Registry To Target Registry
      if: inputs.image-artifact-backend == 'registry'
      shell: bash
      env:
        SOURCE_IMAGE_REF: ${{ steps.build-ref-source-registry.outputs.image-ref }}
        TAGS: ${{ steps.meta.outputs.tags }}
        VERSION: ${{ inputs.version }}
      run: |
        SOURCE_REF_WITH_DIGEST=$(crane digest "${SOURCE_IMAGE_REF}":"${VERSION}" --full-ref)
        echo "Resolving source image reference with digest: [$SOURCE_REF_WITH_DIGEST]"

        for tag in ${TAGS}; do
          crane copy "${SOURCE_REF_WITH_DIGEST}" "${tag}" -v
        done
