name: "Docker Continuous Integration - Generic"

on:
  workflow_call:
    inputs:
      image-artifact-backend:
        type: string
        default: 'registry'
        description: >
          The method used for sharing the image artifact between jobs.
          
          The 'gh-artifacts' method downloads and loads an exported Docker Image Tarball, that was uploaded to GitHub Actions Storage in a previous CI job. 
          The 'registry' method pulls the image from an (snapshot) image registry, that was pushed to the registry in a previous CI job.

          Options:
          - 'gh-artifacts': Share the image artifact as Tarball, uploaded/downloaded via Github Artifact Storage. When this option is used, both `image-build-artifact-name` and `image-tarball-file` are used.
          - 'registry': Share the image artifact via a (snapshot) registry. When this option is used, both `registry-username`, `registry-token` need to be provided or alternatively `token` can be used when the registry is `ghcr.io` and the token has appropriate permissions.

          default: 'registry'
        required: false
      image-artifact-name:
        type: string
        description: >
          Name of the artifact to upload to GitHub Actions Storage, that contains the exported Docker Image Tarball.

          Only required when `image-artifact-backend: 'gh-artifacts'`.

          Default: 'build-docker-image'
        required: false
        default: 'build-docker-image'
      image-artifact-file:
        type: string
        description: >
          Path and filename of the exported Docker Image Tarball, that is to be uploaded to GitHub Actions Storage.

          Only required when `image-artifact-backend: 'gh-artifacts'`.

          Default: 'image.tar'
        required: false
        default: 'image.tar'
      docker-image-repo:
        description: >
          DEPRECATED in favor of `image-repo`.

          Docker image repository. Default -> GitHub repository owner/organisation.
        type: string
        required: false
        default: ${{ github.repository_owner }}
      docker-image-name:
        description: >
          DEPRECATED in favor of `image-name`.

          Docker image name. Default -> GitHub repository name.
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      image-registry:
        description: Image registry prefix (e.g. ghcr.io, docker.io)
        type: string
        required: false
        default: 'ghcr.io'
      image-repo:
        description: >
          Image repository(e.g. wearefrank, my-github-username). Default -> GitHub repository owner/organisation.

          default -> GitHub repository owner/organisation.
        type: string
        required: false
        default: ${{ inputs.docker-image-repo || github.repository_owner }}
      image-name:
        description: >
          Image name(e.g. zaakbrug, frankframework).
          
          default -> GitHub repository name.
        type: string
        required: false
        default: ${{ inputs.docker-image-name || github.event.repository.name }}
      version:
        type: string
        required: false
        description: Semvers string. If empty, the ref/tag will be used (if on.tag trigger).
        default: ''
      latest-tag:
        type: boolean
        required: false
        description: Add latest flavor
        default: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
      upload-sarif-to-security:
        type: boolean
        required: false
        description: Upload Sarif reports to Github Security dashboard
        default: false
      chekov-linter-enabled:
        type: boolean
        required: false
        description: Run Chekov Linter
        default: true
      run-frank-till-healthy-enabled:
        type: boolean
        required: false
        description: Run Frank till the health endpoints returns 'HEALTHY'
        default: true
    secrets:
      token: 
        description: >
          GitHub token with permissions to access the repository.

          default: GitHub token (secrets.GITHUB_TOKEN)
        required: false
      registry-username:
        description: >
          Username for the registry.

          Only required when `image-artifact-backend: 'registry'`.

          default: GitHub actor username (github.actor).
        required: false
      registry-token:
        description: >
          Token for the registry

          Only required when `image-artifact-backend: 'registry'`.
        required: false
    outputs:
      image-id: 
        value: ${{ jobs.build.outputs.image-id }}
      image-digest: 
        value: ${{ jobs.build.outputs.image-digest }}
      bake-file: 
        value: ${{ jobs.build.outputs.bake-file }}
      image-metadata: 
        value: ${{ jobs.build.outputs.image-metadata }}
      docker-meta-tags: 
        value: ${{ jobs.build.outputs.docker-meta-tags }}
      docker-meta-labels: 
        value: ${{ jobs.build.outputs.docker-meta-labels }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    outputs:
      docker-meta-tags: ${{ steps.meta.outputs.tags }}
      docker-meta-labels: ${{ steps.meta.outputs.labels }}
      bake-file: ${{ steps.meta.outputs.json }}
      image-id: ${{ steps.build-tarball.outputs.imageid || steps.build-registry.outputs.imageid }}
      image-digest: ${{ steps.build-tarball.outputs.digest || steps.build-registry.outputs.digest }}
      image-metadata: ${{ steps.build-tarball.outputs.metadata || steps.build-registry.outputs.metadata }}
    steps:
    - uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        disable-sudo: true
        egress-policy: audit
        allowed-endpoints: >
          api.github.com:443
          auth.docker.io:443
          github.com:443
          production.cloudflare.docker.com:443
          registry-1.docker.io:443

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
      with:
        token: ${{ secrets.token }}

    - name: Download Pre-build Artifacts
      uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 #8.0.0
      with:
        pattern: pre-build-*
        merge-multiple: true

    - name: Download Build Artifacts
      uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 #8.0.0
      with:
        pattern: build-*
        merge-multiple: true

    - name: Extract Image Metadata
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 #5.10.0
      with:
        images: ${{ inputs.image-registry }}/${{ inputs.image-repo }}/${{ inputs.image-name }}
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
          type=semver,pattern={{major}},value=${{ inputs.version }}
          type=ref,event=pr
          type=raw,value=latest,enable=${{ inputs.latest-tag }}
        flavor: |
          latest=false

    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 #3.7.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f #3.12.0

    - name: Login to Container Registry
      if: inputs.image-artifact-backend == 'registry'
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # 3.7.0
      with:
        registry: ${{ inputs.image-registry }}
        username: ${{ secrets.registry-username == '' && github.actor || secrets.registry-username }}
        password: ${{ secrets.registry-token == '' && inputs.image-registry == 'ghcr.io' && secrets.token || secrets.registry-token }}

    - name: Build And Export To Tarball
      if: inputs.image-artifact-backend == 'gh-artifacts'
      id: build-tarball
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 #6.19.2
      with:
        context: .
        platforms: linux/amd64
        outputs: type=docker,dest=${{ inputs.image-artifact-file }},oci-mediatypes=true,oci-artifact=true,compression=estargz,compression-level=5,force-compression=true
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Cache Ref
      if: inputs.image-artifact-backend == 'registry'
      id: build-cache-ref
      shell: bash
      env:
        IMAGE_REGISTRY: ${{ inputs.image-registry }}
        IMAGE_REPO: ${{ inputs.image-repo }}
        IMAGE_NAME: ${{ inputs.image-name }}
        IMAGE_TAG: 'buildcache'
      run: |
        IMAGE_REF=""
        if [[ -n "${IMAGE_REGISTRY}" ]]; then
          IMAGE_REF+="${IMAGE_REGISTRY@L}/"
        fi
        if [[ -n "${IMAGE_REPO}" ]]; then
          IMAGE_REF+="${IMAGE_REPO@L}/"
        fi
        if [[ -n "${IMAGE_NAME}" ]]; then
          IMAGE_REF+="${IMAGE_NAME@L}"
        fi

        if [[ -n "${IMAGE_REF}" && -n "${IMAGE_DIGEST}" ]]; then
          IMAGE_REF+="@${IMAGE_DIGEST}"
        elif [[ -n "${IMAGE_REF}" && -n "${IMAGE_TAG}"  ]]; then
          IMAGE_REF+=":${IMAGE_TAG@L}"
        fi

        echo "image-ref=$IMAGE_REF" >> "$GITHUB_OUTPUT"
        echo "Image Ref ([<registry>/][<repo>/]<name>[:<tag>|@<digest>]): [$IMAGE_REF]"

    - name: Build And Push To Registry
      if: inputs.image-artifact-backend == 'registry'
      id: build-registry
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 #6.19.2
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        outputs: type=registry,oci-mediatypes=true,oci-artifact=true,compression=estargz,compression-level=5,force-compression=true
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: true
        sbom: true
        cache-to: type=registry,ref=${{ steps.build-cache-ref.outputs.image-ref }}
        cache-from: type=registry,ref=${{ steps.build-cache-ref.outputs.image-ref }}

    - name: Upload Image Tarball as Artifact
      if: inputs.image-artifact-backend == 'gh-artifacts'
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #7.0.0
      with:
        name: ${{ inputs.image-artifact-name }}
        path: ${{ inputs.image-artifact-file }}
        retention-days: 1

  checkov-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
    if: inputs.chekov-linter-enabled
    steps:
    - uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        disable-sudo: true
        egress-policy: audit
        allowed-endpoints: >
          github.com:443
          pypi.org:443

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
      with:
        token: ${{ secrets.token }}

    - name: Lint Dockerfile with Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@f99709f8ccc3496220c987b7d8729653237c23dc #12.3086.0
      with:
        directory: .
        framework: dockerfile
        check: 'LOW,MEDIUM,HIGH,CRITICAL'
        quiet: false
        soft_fail: true
        output_format: sarif 
        download_external_modules: true
        output_file_path: reports/checkov-results.sarif

    - name: Upload Sarif report as artifact
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #7.0.0
      with:
        name: report-checkov-results
        path: reports/checkov-results.sarif

    - name: Upload to GitHub Security
      uses: github/codeql-action/upload-sarif@89a39a4e59826350b863aa6b6252a07ad50cf83e #4.32.4
      if: inputs.upload-sarif-to-security
      with:
        sarif_file: 'reports/checkov-results.sarif'
    
  # trivy-vulnerability-scan:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   -  
  #     name: "Download Docker tar"
  #     uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 #8.0.0
  #     with:
  #       name: docker
  #       path: .
  #   # - 
  #   #   name: "Load Docker tar"
  #   #   run: |
  #   #     docker image ls -a
  #   #     docker load --input docker.tar
  #   #     docker image ls -a
  #   - 
  #     name: Run Trivy vulnerability scanner
  #     uses: aquasecurity/trivy-action@master
  #     env:
  #       RIVY_OFFLINE_SCAN: true
  #     with:
  #       input: 'docker.tar'
  #       format: 'sarif'
  #       output: 'trivy-results.sarif'
  #       exit-code: '0'
  #       ignore-unfixed: true
  #       vuln-type: 'os,library'
  #       severity: 'CRITICAL'
  #       hide-progress: false
  #   - 
  #     name: "Upload Sarif report as artifact"
  #     uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #7.0.0
  #     with:
  #       name: trivy-results
  #       path: trivy-results.sarif
  #   - 
  #     name: Upload to GitHub Security
  #     uses: github/codeql-action/upload-sarif@v2
  #     if: ${{ inputs.upload-sarif-to-security }}
  #     with:
  #       sarif_file: 'trivy-results.sarif'

  run-till-healthy:
    runs-on: ubuntu-latest
    if: inputs.run-frank-till-healthy-enabled
    permissions:
      contents: read
      packages: read
    needs: build
    steps:
    - uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        disable-sudo: true
        egress-policy: audit
        allowed-endpoints: >
          github.com:443
    
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
      with:
        token: ${{ secrets.token }}

    - name: Download Image Tarball Artifact
      if: inputs.image-artifact-backend == 'gh-artifacts'
      uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 #8.0.0
      with:
        name: ${{ inputs.image-artifact-name }}

    - name: Load Docker Tarball
      if: inputs.image-artifact-backend == 'gh-artifacts'
      shell: bash
      run: |
        docker load --input ${{ inputs.image-artifact-file }}
        docker images -a --digests

    - name: Login to Container Registry
      if: inputs.image-artifact-backend == 'registry'
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # 3.7.0
      with:
        registry: ${{ inputs.image-registry }}
        username: ${{ secrets.registry-username == '' && github.actor || secrets.registry-username }}
        password: ${{ secrets.registry-token == '' && inputs.image-registry == 'ghcr.io' && secrets.token || secrets.registry-token }}

    - name: Build Image Ref
      id: build-image-ref
      shell: bash
      env:
        IMAGE_REGISTRY: ${{ inputs.image-registry }}
        IMAGE_REPO: ${{ inputs.image-repo }}
        IMAGE_NAME: ${{ inputs.image-name }}
        IMAGE_DIGEST: ${{ needs.build.outputs.image-digest }}
        IMAGE_TAG: ${{ inputs.version != '' && inputs.version || github.ref_name }}
      run: |
        IMAGE_REF=""
        if [[ -n "${IMAGE_REGISTRY}" ]]; then
          IMAGE_REF+="${IMAGE_REGISTRY@L}/"
        fi
        if [[ -n "${IMAGE_REPO}" ]]; then
          IMAGE_REF+="${IMAGE_REPO@L}/"
        fi
        if [[ -n "${IMAGE_NAME}" ]]; then
          IMAGE_REF+="${IMAGE_NAME@L}"
        fi

        if [[ -n "${IMAGE_REF}" && -n "${IMAGE_DIGEST}" ]]; then
          IMAGE_REF+="@${IMAGE_DIGEST}"
        elif [[ -n "${IMAGE_REF}" && -n "${IMAGE_TAG}"  ]]; then
          IMAGE_REF+=":${IMAGE_TAG@L}"
        fi

        echo "image-ref=$IMAGE_REF" >> "$GITHUB_OUTPUT"
        echo "Image Ref ([<registry>/][<repo>/]<name>[:<tag>|@<digest>]): [$IMAGE_REF]"

    - name: Pull Image From Registry
      if: inputs.image-artifact-backend == 'registry'
      shell: bash
      env:
        IMAGE_REF: ${{ steps.build-image-ref.outputs.image-ref }}
      run: |
        echo "Pulling image from registry with ref: [${IMAGE_REF}]"
        docker pull "${IMAGE_REF}"

    - name: Run Till Healthy
      uses: wearefrank/ci-cd-templates/frank-run-till-healthy@a85b79cdca04aad14e78a668220e8dcda0c3ebd3 #2.2.0
      with:
        image-ref: ${{ steps.build-image-ref.outputs.image-ref }}

