name: SoapUI TestRunner

on:
  workflow_call:
    inputs:
      image-artifact-backend:
        type: string
        default: 'registry'
        description: >
          The method used for sharing the image artifact between jobs.
          
          The 'gh-artifacts' method downloads and loads an exported Docker Image Tarball, that was uploaded to GitHub Actions Storage in a previous CI job. 
          The 'registry' method pulls the image from an (snapshot) image registry, that was pushed to the registry in a previous CI job.

          Options:
          - 'gh-artifacts': Share the image artifact as Tarball, uploaded/downloaded via Github Artifact Storage. When this option is used, both `image-build-artifact-name` and `image-tarball-file` are used.
          - 'registry': Share the image artifact via a (snapshot) registry. When this option is used, both `registry-username`, `registry-token` need to be provided or alternatively `token` can be used when the registry is `ghcr.io` and the token has appropriate permissions.

          default: 'registry'
        required: false
      image-artifact-name:
        type: string
        description: >
          Name of the artifact uploaded to GitHub Actions Storage, that contains the exported Docker Image Tarball.

          Only required when `image-artifact-backend: 'gh-artifacts'`.

          Default: 'build-docker-image'
        required: false
        default: 'build-docker-image'
      image-artifact-file:
        type: string
        description: >
          Path and filename of the exported Docker Image Tarball, that was uploaded to GitHub Actions Storage.

          Only required when `image-artifact-backend: 'gh-artifacts'`.

          Default: 'image.tar'
        required: false
        default: 'image.tar'
      image-id:
        type: string
        description: >
          Image id of the application under test.

          Note: An image id is the hash of the local image json configuration and may differ across environments and runs.
        required: false
      image-ref:
        type: string
        description: >
          Image reference of the application under test according to the [OCI Image Reference Format](https://docs.docker.com/reference/compose-file/services/#image) as `[<registry>/][<project>/]<image>[:<tag>|@<digest>]`.
          For example: 'docker.io/wearefrank/zaakbrug:1.2.0'.

          Warning: Using `image-ref` without a digest could resolve to an already released image if the CI built image is not available in the local Docker engine.
        required: false
      upload-larva-testreport-artifact:
        type: boolean
        description: >
          When 'true', the Larva testreport will be uploaded as a GitHub Artifact

          Default: true
        required: false
        default: true
      larva-testreport-artifact-name:
        type: string
        description: >
          Name of the GitHub Artifact the Larva testreport should be uploaded under.

          Default: reports-larva-testreport
        required: false
        default: 'reports-larva-testreport'
      larva-testreport-to-actions-summary:
        type: boolean
        description: >
          When 'true', the Larva testreport will be printed to the GitHub Actions Summary.

          Default: true
        required: false
        default: true
      larva-loglevel:
        type: string
        description: >
          Log level for Larva test execution.

          Default: 'WRONG_PIPELINE_MESSAGES_PREPARED_FOR_DIFF'
        required: false
        default: 'WRONG_PIPELINE_MESSAGES_PREPARED_FOR_DIFF'
      larva-execution-target:
        type: string
        description: >
          Path to the directory containing the Larva scenarios to be executed, relative to the container's filesystem.

          Default: '/opt/frank/testtool'
        required: false
        default: '/opt/frank/testtool'
      setup-script:
        type: string
        description: >
          A 'Setup' script to bring up the application/environment under test. The script must be non-blocking.

          Examples:
          Docker Compose(with `service.image: ${IMAGE_ID:-${IMAGE_REF:-<registry>/<organisation>/<image-name>}}`):
          ```bash
            docker compose -f 'compose.frank.yaml' -f 'compose.frank.ci.yaml' up -d
          ```
          Docker:
          ```bash
            docker run -d ${IMAGE_ID:-${IMAGE_REF:-<registry>/<organisation>/<image-name>}}
          ```

          Warning: It is very important that the Docker image built in CI is used. The 'Setup' script should never build the Docker Image.
          The environment variables `IMAGE_ID` and/or `IMAGE_REF` are available in the 'Setup' script depending on which one(s) is/are provided to
          this workflow. "image-ref" with a digest is recommended to ensure the correct image is used.
        required: false
      teardown-script:
        type: string
        description: >
          A 'Teardown' script to stop and cleanup up the application/environment under test. The script must be non-blocking.

          The environment variables `CONTAINER_ID`,`IMAGE_ID` and/or `IMAGE_REF` are made available for stopping/cleaning up the used container afterwards.

          Examples:
          Docker Compose:
          ```bash
            docker compose -f 'compose.frank.yaml' -f 'compose.frank.ci.yaml' down -v
          ```
          Docker:
          ```bash
            docker stop ${CONTAINER_ID}
            docker rm --volumes ${CONTAINER_ID}
          ```
        required: false
    secrets:
      token: 
        description: >
          GitHub token with permissions to access the repository.

          default: GitHub token (secrets.GITHUB_TOKEN)
        required: false
      registry-username:
        description: >
          Username for the registry.

          Only required when `image-artifact-backend: 'registry'`.

          default: GitHub actor username (github.actor).
        required: false
      registry-token:
        description: >
          Token for the registry

          Only required when `image-artifact-backend: 'registry'`.
        required: false

jobs:
  larva-testrunner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
        with:
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
      
      - name: Download Image Tarball Artifact
        if: inputs.image-artifact-backend == 'gh-artifacts'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #8.0.1
        with:
          name: ${{ inputs.image-artifact-name }}

      - name: Load Docker Tarball
        if: inputs.image-artifact-backend == 'gh-artifacts'
        shell: bash
        env:
          TARBALL_FILE: ${{ inputs.image-artifact-file }}
        run: |
          docker load --input "${TARBALL_FILE}"
          docker images -a --digests

      - name: Parse Image Ref
        id: parse-image-ref
        if: inputs.image-artifact-backend == 'registry'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 #9.0.0
        with:
          debug: true
          script: |
            const inputs = ${{ toJSON(inputs) }};
            console.log(`Received inputs: ${JSON.stringify(inputs)}`);

            const imageRef = inputs['image-ref'];
            console.log(`Parsing image reference: [${imageRef}]`);

            const imageRefPattern = new RegExp('^(?:(?<registry>[^\/]+)\/)?(?:(?<repo>[^\/]+)\/)?(?<name>[^:@]+)(?:(?::(?<tag>[^@]+))|(?:@(?<digest>.+)))?$');
            var matchPattern;
            try {
              matchPattern = imageRef.match(imageRefPattern);
            } catch (error) {
              core.setFailed(`Failed to parse image reference: [${imageRef}]. Error: ${error.message}`);
              return;
            }
            
            console.log(`Parsed image reference: registry=[${matchPattern?.groups?.registry}], repo=[${matchPattern?.groups?.repo}], name=[${matchPattern?.groups?.name}], tag=[${matchPattern?.groups?.tag}], digest=[${matchPattern?.groups?.digest}]`);
            core.setOutput('image-registry', matchPattern?.groups?.registry);
            core.setOutput('image-repo', matchPattern?.groups?.repo);
            core.setOutput('image-name', matchPattern?.groups?.name);
            core.setOutput('image-tag', matchPattern?.groups?.tag);
            core.setOutput('image-digest', matchPattern?.groups?.digest);

      - name: Login to Container Registry
        if: inputs.image-artifact-backend == 'registry'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # 4.1.0
        with:
          registry: ${{ steps.parse-image-ref.outputs.image-registry }}
          username: ${{ secrets.registry-username == '' && github.actor || secrets.registry-username }}
          password: ${{ secrets.registry-token == '' && steps.parse-image-ref.outputs.image-registry == 'ghcr.io' && secrets.token || secrets.registry-token }}

      - name: Pull Image From Registry
        if: inputs.image-artifact-backend == 'registry'
        shell: bash
        env:
          IMAGE_REF: ${{ inputs.image-ref }}
        run: |
          echo "Pulling image from registry with ref: [${IMAGE_REF}]"
          docker pull "${IMAGE_REF}"

      - name: Setup Test Environment
        if: inputs.setup-script
        shell: bash
        env:
          IMAGE_ID: ${{ inputs.image-id }}
          IMAGE_TAG: ${{ inputs.image-ref }}
          IMAGE_REF: ${{ inputs.image-ref }}
        run: "${{ inputs.setup-script }}"
      
      - name: Wait Till Healthy Container
        id: wait-till-healthy
        uses: wearefrank/ci-cd-templates/wait-till-healthy-container@00b8c33dd29ef328ad7aa1a2732dc6f41f2e03f3 #2.4.10
        with:
          image-id: ${{ inputs.image-id }}
          image-name: ${{ inputs.image-ref }}

      - name: Run Larva Tests
        uses: wearefrank/ci-cd-templates/larva-testrunner@00b8c33dd29ef328ad7aa1a2732dc6f41f2e03f3 #2.4.10
        timeout-minutes: 5
        with:
          container-id: ${{ steps.wait-till-healthy.outputs.container-id }}
          upload-larva-testreport-artifact: ${{ inputs.upload-larva-testreport-artifact }}
          larva-testreport-artifact-name: ${{ inputs.larva-testreport-artifact-name }}
          larva-testreport-to-actions-summary: ${{ inputs.larva-testreport-to-actions-summary }}
          larva-loglevel: ${{ inputs.larva-loglevel }}
          larva-execution-target: ${{ inputs.larva-execution-target }}
      
      - name: Docker Inspect, Stats And Logs
        if: failure() || runner.debug == '1'
        env:
          IMAGE_ID: ${{ inputs.image-id }}
          IMAGE_TAG: ${{ inputs.image-ref }}
          IMAGE_REF: ${{ inputs.image-ref }}
          CONTAINER_ID: ${{ steps.wait-till-healthy.outputs.container-id }}
        shell: bash
        run: |
          docker inspect "$CONTAINER_ID"
          docker logs "$CONTAINER_ID"
          docker stats --no-stream "$CONTAINER_ID"
      
      - name: Teardown Test Environment
        if: always() && inputs.teardown-script
        shell: bash
        env:
          CONTAINER_ID: ${{ steps.wait-till-healthy.outputs.container-id }}
        run: "${{ inputs.teardown-script }}"
